# Travis CI configuration file

language: python

python:
  - "3.4"
  - "3.5"


notifications:
  email: false

dist:
  - stable
  - trusty

sudo: required

cache:
  timeout: 1500
  pip: true

addons:
  apt:
    packages:
      - wget
      - texlive-full
      - optipng
      - inkscape

install:
  - travis_wait pip install -r requirements.txt

script:
  - make
