# Travis CI configuration file

language: python

python:
  - "3.4"

notifications:
  email: false

dist: trusty

sudo: false

cache:
  timeout: 1500
  pip: true

addons:
  apt:
    packages:
      - wget
      - texlive-full
      - optipng
      - inkscape

#before_install:

install:
  - travis_wait pip install requirements.txt

script:
  - make
